repos:
  # 1. Standard file fixing
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # <--- This saves your life with OpenAPI
      - id: check-added-large-files

  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev: 0.8.0b1
    hooks:
      - id: openapi-spec-validator
        args: ["openapi.yaml"]
